config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :staffs, controllers: {
        registrations: 'staff/registrations'
      }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'page#index'

  get "/api/houses" => 'api#houses'
  get "/api/houses/activities" => 'api#house_points_by_activity'
  get "/api/staff" => 'api#staff'
  get "/api/staff/:id" => 'api#specific_staff'
  get "/api/staff/activities" => 'api#staff_assignment_by_activity'
  get "/api/members" => 'api#members'
  get "/api/members/top" => 'api#top_members'
  get "/api/members/bottom" => 'api#bottom_members'
  get "/api/members/:id" => 'api#member'
  get "/api/houses" => 'api#houses'
  get "/api/top_points" => 'api#top_points'
  post "/api/behavior_report" => "api#member_behavior_report"

  get "/students" => 'page#students'

  get ':school' => 'page#show'
  get ':school/stylesheet' => 'page#stylesheet'
  get ':school/about' => 'page#about'

  get ':school/score' => 'page#add'
  post ':school/score' => 'page#doadd'

  get ':school/house/:id' => 'page#invite'
  post ':school/house/:id' => 'page#doinvite'

  get ':school/invite' => 'page#create_invite'
  post ':school/invite' => 'page#do_create_invite'

end

app/views/layouts/api.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	  <link href="<%= root_url %>css/pdf.css" media="all" rel="stylesheet" />
	</head>
	<body>
		<div class="container" id="content">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HouseCup</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/bs-3.3.5/dt-1.10.9,af-2.0.0,fh-3.0.0,r-1.0.7/datatables.min.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if @school != nil %>
  	<link href="/<%= @school.url %>/stylesheet" media="all" rel="stylesheet">
  <% end %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <a class="navbar-brand">
	      	<% if @school.nil? %>
	      		The Gradery
	      	<% else %>
	      		<%= @school.name %>
	      	<% end %>
	      </a>
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<% if @school.nil? %>
	      		<li><a href="/">Home</a></li>
	      		<li><a href="mailto:support@gradery.com">Support</a></li>
	      	<% else %>
	      		<li><a href="/<%= @school.url%>">Home</a></li>
	      		<li><a href="/<%= @school.url%>/about">About</a></li>
	      		<li><a href="mailto:support@gradery.com">Support</a></li>
	      	<% end %>
	        <% if current_staff.nil? %>
	      		<li><a href="/staffs/sign_in">Login</a></li>
	      	<% else %>
	      	    <% if !@school.nil? %>
	      		<li><a href="/<%= @school.url%>/score">Score</a></li>
	      		<% end %>
	      		<li><a href="/staffs/edit">My Profile</a></li>
	      	<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="container" id="content">
		<p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
		<%= yield %>
	</div>

</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script type="text/javascript" src="https://cdn.datatables.net/r/bs/dt-1.10.9,af-2.0.0,fh-3.0.0,r-1.0.7/datatables.min.js"></script>
</html>